name: Deploy Frontend

on:
  push:
    branches:
      - restructure/webpack-pnpm-express

jobs:
    deploy:
        runs-on: ubuntu-latest
        container:
            image: node:22
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v4
              with:
                version: 10
            - name: Build with webpack
              run: pnpm -C ./frontend/ install && pnpm -C ./frontend/ run build
            - name: Get SSH Key and set permissions
              run: |
                mkdir -p ~/.ssh/
                echo "${{ secrets.SSH_USERSTATIC_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
            - name: Clear root directory
              run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USERAPI }}@${{ secrets.SSH_HOST }} "rm -rf /home/${{ secrets.SSH_USERAPI }}/htdocs/api.destinyarticlefinder.com/*"
            - name: Deploy using SCP
              run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./frontend/dist/* ${{ secrets.SSH_USERSTATIC }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USERSTATIC }}/htdocs/www.destinyarticlefinder.com/
            
