name: Deploy-Test

on:
    push:
        branches:
            - github-actions

jobs:
    test:
        runs-on: ubuntu-latest
        container: 
            image: node:20
        steps:
            - uses: actions/checkout@v3
              with:
                node-version: 20
            - run: npm ci
            - run: npm run build
            - name: Get SSH Key and set permissions
              run: |
                mkdir -p ~/.ssh/
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
            - name: Deploy using SCP
              run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./client/build ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:./home/${{ secrets.SSH_USER }}/htdocs/www.destinyarticlefinder.com/client/