name: Deploy-Test

on:
    push:
        branches:
            - github-actions

jobs:
    test:
        runs-on: ubuntu-latest
        container: 
            image: node:20
        steps:
            - uses: actions/checkout@v3
              with:
                node-version: 20
            - run: npm ci
            - run: npm run build
            - name: Get SSH Key and set permissions
              run: |
                mkdir -p ~/.ssh/
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                chmod 700 ~/.ssh
            - name: Install rsync and sshpass
              run: apt-get update && apt-get install -y rsync sshpass
            - name: Add remote server to known_hosts
              run: |
                ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            - name: Deploy using rsync
              run: |
                sshpass -p "${{ secrets.SSH_PASSPHRASE }}" rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/htdocs/www.destinyarticlefinder.com/client